const menu = [
  {
    id: 1,
    title: 'Eiffel Tower',
    category: 'paris',
    price: 1.6,
    img: './images/item-1.jpg',
    desc: `The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel. `,
  },
  {
    id: 2,
    title: 'Château de Versailles',
    category: 'paris',
    price: 0.6,
    img: './images/item-2.jpg',
    desc: `The Palace of Versailles is a former royal residence located in Versailles, about 12 miles west of Paris, France. `,
  },
  {
    id: 3,
    title: 'Arc de Triomphe',
    category: 'paris',
    price: 1.5,
    img: './images/item-3.jpg',
    desc: `The Arc de Triomphe de l'Étoile is one of the most famous monuments in Paris, France, standing at the western end of the Champs-Élysées at the centre of Place Charles de Gaulle.`,
  },
  {
    id: 4,
    title: 'Gamla Stan',
    category: 'stockholm',
    price: 2.7,
    img: './images/item-4.jpg',
    desc: `The bustling, compact island of Gamla Stan is the city’s old town, with cobbled streets and colorful 17th- and 18th-century buildings. `,
  },
  {
    id: 5,
    title: 'Vasa Museum',
    category: 'stockholm',
    price: 4.0,
    img: './images/item-5.jpg',
    desc: `The Vasa is the best-preserved seventeenth-century ship in the world and a unique art treasure.`,
  },
  {
    id: 6,
    title: 'Sveriges Kungahus',
    category: 'stockholm',
    price: 3.3,
    img: './images/item-6.jpg',
    desc: `Kungliga huset, eller kungahuset, består av statschefen.`,
  },
  {
    id: 7,
    title: 'Nyhavn',
    category: 'copenhagen',
    price: 1.8,
    img: './images/item-7.jpg',
    desc: `Colourful, captivating Nyhavn is one of Copenhagen's most iconic sights and one of the locals' favourite places to sink a cold beer on a hot day. `,
  },
  {
    id: 8,
    title: 'SMK',
    category: 'copenhagen',
    price: 2.1,
    img: './images/item-8.jpg',
    desc: `This gallery houses the national collection of paintings.`,
  },
  {
    id: 9,
    title: 'Gamla Uppsala',
    category: 'uppsala',
    price: 1.9,
    img: './images/item-9.jpg',
    desc: `Gamla Uppsala Church (Gamla Uppsala kyrka) was the seat of the Archbishopric of Sweden prior to 1273.`,
  },
  {
    id: 10,
    title: 'Uppsala Cathedral',
    category: 'uppsala',
    price: 2.8,
    img: './images/item-10.jpg',
    desc: `Uppsala Cathedral is the largest and tallest cathedral and one of the most impressive religious buildings in Scandinavia.`,
  },
];
export default menu;
